import { NextResponse } from "next/server";

// Sandbox API for LMS Courses
const MOCK_COURSES = [
  {
    id: "course-brand-guidelines",
    title: "LMTD Brand Guidelines",
    slug: "brand-guidelines",
    description: "Learn our brand identity, visual standards, and communication guidelines for all client-facing materials. This comprehensive course covers everything from logo usage to typography.",
    shortDescription: "Master the LMTD brand identity",
    category: "Onboarding",
    tags: ["brand", "design", "guidelines", "onboarding"],
    skillLevel: "Beginner",
    status: "PUBLISHED",
    visibility: "PRIVATE",
    thumbnailUrl: null,
    estimatedDuration: 45, // minutes
    moduleCount: 2,
    lessonCount: 4,
    enrollmentCount: 38,
    completionCount: 32,
    avgRating: 4.7,
    ratingCount: 28,
    hasCertificate: true,
    passingScore: 80,
    instructor: { id: "user-sarah", name: "Sarah Mitchell", title: "Creative Director" },
    publishedAt: "2024-01-15T10:00:00Z",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-11-01T14:00:00Z",
    modules: [
      {
        id: "mod-brand-1",
        title: "Introduction to Our Brand",
        description: "Understanding what makes LMTD unique",
        sortOrder: 1,
        lessonCount: 2,
        lessons: [
          { id: "les-1", title: "Welcome to LMTD", type: "VIDEO", duration: 5 },
          { id: "les-2", title: "Our Mission & Values", type: "ARTICLE", duration: 10 },
        ],
      },
      {
        id: "mod-brand-2",
        title: "Visual Identity",
        description: "Logo, colors, and typography",
        sortOrder: 2,
        lessonCount: 2,
        lessons: [
          { id: "les-3", title: "Logo Usage Guidelines", type: "DOCUMENT", duration: 8 },
          { id: "les-4", title: "Color Palette & Typography", type: "ARTICLE", duration: 7 },
        ],
      },
    ],
  },
  {
    id: "course-social-media",
    title: "Social Media Best Practices",
    slug: "social-media-best-practices",
    description: "Master social media marketing strategies and content creation for modern platforms. Learn platform-specific strategies, content creation techniques, and analytics interpretation.",
    shortDescription: "Master social media marketing",
    category: "Marketing",
    tags: ["social media", "marketing", "content", "analytics"],
    skillLevel: "Intermediate",
    status: "PUBLISHED",
    visibility: "PRIVATE",
    thumbnailUrl: null,
    estimatedDuration: 90,
    moduleCount: 2,
    lessonCount: 4,
    enrollmentCount: 45,
    completionCount: 38,
    avgRating: 4.8,
    ratingCount: 35,
    hasCertificate: true,
    passingScore: 75,
    instructor: { id: "user-marcus", name: "Marcus Chen", title: "Social Media Lead" },
    publishedAt: "2024-02-01T10:00:00Z",
    createdAt: "2024-01-25T11:00:00Z",
    updatedAt: "2024-10-15T09:00:00Z",
    modules: [
      {
        id: "mod-social-1",
        title: "Platform Fundamentals",
        description: "Understanding each social platform",
        sortOrder: 1,
        lessonCount: 3,
        lessons: [
          { id: "les-5", title: "Instagram Strategy", type: "VIDEO", duration: 15 },
          { id: "les-6", title: "LinkedIn for B2B", type: "VIDEO", duration: 12 },
          { id: "les-7", title: "TikTok & Short-Form Video", type: "VIDEO", duration: 18 },
        ],
      },
      {
        id: "mod-social-2",
        title: "Content Creation",
        description: "Creating engaging content",
        sortOrder: 2,
        lessonCount: 1,
        lessons: [
          { id: "les-8", title: "Writing Engaging Captions", type: "ARTICLE", duration: 10 },
        ],
      },
    ],
  },
  {
    id: "course-client-comms",
    title: "Effective Client Communication",
    slug: "client-communication",
    description: "Build stronger client relationships through professional communication techniques. Master the art of setting expectations, handling difficult conversations, and building lasting relationships.",
    shortDescription: "Master client relationships",
    category: "Soft Skills",
    tags: ["communication", "client relations", "soft skills"],
    skillLevel: "Beginner",
    status: "DRAFT",
    visibility: "PRIVATE",
    thumbnailUrl: null,
    estimatedDuration: 60,
    moduleCount: 1,
    lessonCount: 1,
    enrollmentCount: 0,
    completionCount: 0,
    avgRating: null,
    ratingCount: 0,
    hasCertificate: true,
    passingScore: 70,
    instructor: { id: "user-amanda", name: "Amanda Roberts", title: "Account Director" },
    publishedAt: null,
    createdAt: "2024-11-01T10:00:00Z",
    updatedAt: "2024-12-15T14:00:00Z",
    modules: [
      {
        id: "mod-client-1",
        title: "Communication Fundamentals",
        description: "Core principles of client communication",
        sortOrder: 1,
        lessonCount: 1,
        lessons: [
          { id: "les-9", title: "Setting Expectations", type: "VIDEO", duration: 12 },
        ],
      },
    ],
  },
  {
    id: "course-video-production",
    title: "Video Production Essentials",
    slug: "video-production",
    description: "Learn professional video production from pre-production planning to final delivery. Covers equipment, lighting, sound, editing, and delivery best practices.",
    shortDescription: "Professional video production skills",
    category: "Technical Skills",
    tags: ["video", "production", "editing", "technical"],
    skillLevel: "Intermediate",
    status: "PUBLISHED",
    visibility: "PRIVATE",
    thumbnailUrl: null,
    estimatedDuration: 180,
    moduleCount: 4,
    lessonCount: 20,
    enrollmentCount: 28,
    completionCount: 15,
    avgRating: 4.9,
    ratingCount: 14,
    hasCertificate: true,
    passingScore: 80,
    instructor: { id: "user-david", name: "David Park", title: "Video Production Lead" },
    publishedAt: "2024-03-01T10:00:00Z",
    createdAt: "2024-02-15T09:00:00Z",
    updatedAt: "2024-11-20T11:00:00Z",
    modules: [
      {
        id: "mod-video-1",
        title: "Pre-Production",
        description: "Planning and preparation",
        sortOrder: 1,
        lessonCount: 5,
        lessons: [
          { id: "les-10", title: "Project Scoping", type: "VIDEO", duration: 10 },
          { id: "les-11", title: "Storyboarding", type: "ARTICLE", duration: 15 },
          { id: "les-12", title: "Location Scouting", type: "VIDEO", duration: 12 },
          { id: "les-13", title: "Equipment Checklist", type: "DOCUMENT", duration: 8 },
          { id: "les-14", title: "Call Sheets & Scheduling", type: "ARTICLE", duration: 10 },
        ],
      },
      {
        id: "mod-video-2",
        title: "Production",
        description: "On-set techniques",
        sortOrder: 2,
        lessonCount: 5,
        lessons: [
          { id: "les-15", title: "Camera Fundamentals", type: "VIDEO", duration: 20 },
          { id: "les-16", title: "Lighting Techniques", type: "VIDEO", duration: 25 },
          { id: "les-17", title: "Audio Recording", type: "VIDEO", duration: 15 },
          { id: "les-18", title: "Directing Talent", type: "VIDEO", duration: 18 },
          { id: "les-19", title: "B-Roll Strategies", type: "VIDEO", duration: 12 },
        ],
      },
    ],
  },
  {
    id: "course-project-management",
    title: "Agency Project Management",
    slug: "project-management",
    description: "Master project management methodologies tailored for creative agencies. Learn agile workflows, resource planning, timeline management, and client communication.",
    shortDescription: "PM skills for creative agencies",
    category: "Leadership",
    tags: ["project management", "agile", "leadership", "planning"],
    skillLevel: "Advanced",
    status: "PUBLISHED",
    visibility: "PRIVATE",
    thumbnailUrl: null,
    estimatedDuration: 120,
    moduleCount: 3,
    lessonCount: 15,
    enrollmentCount: 22,
    completionCount: 18,
    avgRating: 4.6,
    ratingCount: 16,
    hasCertificate: true,
    passingScore: 75,
    instructor: { id: "user-jennifer", name: "Jennifer Walsh", title: "Operations Director" },
    publishedAt: "2024-04-01T10:00:00Z",
    createdAt: "2024-03-15T09:00:00Z",
    updatedAt: "2024-10-01T14:00:00Z",
    modules: [
      {
        id: "mod-pm-1",
        title: "Project Initiation",
        description: "Starting projects right",
        sortOrder: 1,
        lessonCount: 5,
        lessons: [
          { id: "les-20", title: "Scoping & Requirements", type: "VIDEO", duration: 15 },
          { id: "les-21", title: "Stakeholder Mapping", type: "ARTICLE", duration: 10 },
          { id: "les-22", title: "Risk Assessment", type: "VIDEO", duration: 12 },
          { id: "les-23", title: "Resource Planning", type: "ARTICLE", duration: 15 },
          { id: "les-24", title: "Kickoff Best Practices", type: "VIDEO", duration: 10 },
        ],
      },
    ],
  },
];

export async function GET() {
  await new Promise((resolve) => setTimeout(resolve, 100));

  const published = MOCK_COURSES.filter((c) => c.status === "PUBLISHED");

  return NextResponse.json({
    data: MOCK_COURSES,
    meta: {
      total: MOCK_COURSES.length,
      published: published.length,
      totalEnrollments: MOCK_COURSES.reduce((sum, c) => sum + c.enrollmentCount, 0),
      totalCompletions: MOCK_COURSES.reduce((sum, c) => sum + c.completionCount, 0),
      avgRating:
        published.filter((c) => c.avgRating).length > 0
          ? (
              published.filter((c) => c.avgRating).reduce((sum, c) => sum + (c.avgRating || 0), 0) /
              published.filter((c) => c.avgRating).length
            ).toFixed(1)
          : null,
      byCategory: {
        Onboarding: MOCK_COURSES.filter((c) => c.category === "Onboarding").length,
        Marketing: MOCK_COURSES.filter((c) => c.category === "Marketing").length,
        "Technical Skills": MOCK_COURSES.filter((c) => c.category === "Technical Skills").length,
        Leadership: MOCK_COURSES.filter((c) => c.category === "Leadership").length,
        "Soft Skills": MOCK_COURSES.filter((c) => c.category === "Soft Skills").length,
      },
    },
    sandbox: true,
  });
}

export async function POST(request: Request) {
  const body = await request.json();

  const newCourse = {
    id: `course-${Date.now()}`,
    title: body.title || "New Course",
    slug: body.slug || `course-${Date.now()}`,
    description: body.description || "",
    shortDescription: body.shortDescription || "",
    category: body.category || "Uncategorized",
    tags: body.tags || [],
    skillLevel: body.skillLevel || "Beginner",
    status: "DRAFT",
    visibility: body.visibility || "PRIVATE",
    thumbnailUrl: null,
    estimatedDuration: 0,
    moduleCount: 0,
    lessonCount: 0,
    enrollmentCount: 0,
    completionCount: 0,
    avgRating: null,
    ratingCount: 0,
    hasCertificate: body.hasCertificate || false,
    passingScore: body.passingScore || 70,
    instructor: { id: "sandbox-user", name: "Sandbox User", title: "Instructor" },
    publishedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    modules: [],
  };

  return NextResponse.json({
    data: newCourse,
    sandbox: true,
    message: "Course created (sandbox mode - not persisted)",
  });
}
