import { NextResponse } from "next/server";

// Sandbox API for Form Templates
const MOCK_TEMPLATES = [
  {
    id: "tmpl-client-sat",
    name: "Client Satisfaction Survey",
    description: "Comprehensive survey to measure client satisfaction and gather feedback on our services.",
    kind: "SURVEY",
    category: "CLIENT_SATISFACTION",
    isPublished: true,
    isDefault: true,
    version: 3,
    questionCount: 12,
    estimatedTime: 5,
    usageCount: 24,
    lastUsedAt: "2024-12-28T10:00:00Z",
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2024-11-01T14:00:00Z",
    createdBy: { id: "user-1", name: "Will Hutchinson" },
    questions: [
      { id: "q1", type: "RATING", label: "Overall satisfaction with our services", required: true },
      { id: "q2", type: "NPS", label: "How likely are you to recommend us?", required: true },
      { id: "q3", type: "MULTIPLE_CHOICE", label: "Which services have you used?", required: true },
      { id: "q4", type: "TEXT", label: "What do we do best?", required: false },
      { id: "q5", type: "TEXT", label: "How can we improve?", required: false },
    ],
  },
  {
    id: "tmpl-employee-eng",
    name: "Employee Engagement",
    description: "Annual survey to measure employee satisfaction, engagement, and workplace culture.",
    kind: "SURVEY",
    category: "EMPLOYEE_ENGAGEMENT",
    isPublished: true,
    isDefault: false,
    version: 2,
    questionCount: 25,
    estimatedTime: 10,
    usageCount: 4,
    lastUsedAt: "2024-11-01T09:00:00Z",
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-10-15T11:00:00Z",
    createdBy: { id: "user-2", name: "Afaq Ahmed" },
    questions: [
      { id: "q1", type: "RATING", label: "I feel valued at work", required: true },
      { id: "q2", type: "RATING", label: "I have the tools I need to do my job", required: true },
      { id: "q3", type: "RATING", label: "My manager supports my development", required: true },
      { id: "q4", type: "RATING", label: "I understand how my work contributes to company goals", required: true },
      { id: "q5", type: "TEXT", label: "What would make this a better place to work?", required: false },
    ],
  },
  {
    id: "tmpl-quick-poll",
    name: "Quick Poll",
    description: "Simple poll template for quick team decisions and preferences.",
    kind: "POLL",
    category: "INTERNAL_PROCESS",
    isPublished: true,
    isDefault: false,
    version: 1,
    questionCount: 1,
    estimatedTime: 1,
    usageCount: 15,
    lastUsedAt: "2024-12-28T11:00:00Z",
    createdAt: "2024-03-10T14:00:00Z",
    updatedAt: "2024-03-10T14:00:00Z",
    createdBy: { id: "user-3", name: "CJ Caruncho" },
    questions: [
      { id: "q1", type: "MULTIPLE_CHOICE", label: "Select your preference", required: true },
    ],
  },
  {
    id: "tmpl-project-feedback",
    name: "Project Feedback",
    description: "Post-project survey to gather client feedback on deliverables and process.",
    kind: "SURVEY",
    category: "CLIENT_SATISFACTION",
    isPublished: true,
    isDefault: false,
    version: 2,
    questionCount: 8,
    estimatedTime: 4,
    usageCount: 12,
    lastUsedAt: "2024-12-15T09:00:00Z",
    createdAt: "2024-04-01T10:00:00Z",
    updatedAt: "2024-09-01T11:00:00Z",
    createdBy: { id: "user-1", name: "Will Hutchinson" },
    questions: [
      { id: "q1", type: "RATING", label: "Quality of deliverables", required: true },
      { id: "q2", type: "RATING", label: "Communication throughout the project", required: true },
      { id: "q3", type: "RATING", label: "Timeliness of delivery", required: true },
      { id: "q4", type: "RATING", label: "Value for investment", required: true },
      { id: "q5", type: "TEXT", label: "Additional comments", required: false },
    ],
  },
  {
    id: "tmpl-onboarding",
    name: "Onboarding Experience",
    description: "Feedback survey for new hires to evaluate the onboarding process.",
    kind: "FEEDBACK",
    category: "ONBOARDING",
    isPublished: true,
    isDefault: false,
    version: 1,
    questionCount: 10,
    estimatedTime: 5,
    usageCount: 8,
    lastUsedAt: "2024-12-20T10:00:00Z",
    createdAt: "2024-01-01T09:00:00Z",
    updatedAt: "2024-06-01T14:00:00Z",
    createdBy: { id: "user-4", name: "HR Team" },
    questions: [
      { id: "q1", type: "RATING", label: "Pre-arrival communication", required: true },
      { id: "q2", type: "RATING", label: "First day experience", required: true },
      { id: "q3", type: "RATING", label: "Training effectiveness", required: true },
      { id: "q4", type: "RATING", label: "Manager support", required: true },
      { id: "q5", type: "TEXT", label: "What would improve the onboarding experience?", required: false },
    ],
  },
  {
    id: "tmpl-event-feedback",
    name: "Event Feedback",
    description: "Post-event survey to gather attendee feedback and suggestions.",
    kind: "FEEDBACK",
    category: "EVENT_FEEDBACK",
    isPublished: true,
    isDefault: false,
    version: 1,
    questionCount: 6,
    estimatedTime: 3,
    usageCount: 3,
    lastUsedAt: "2024-11-15T16:00:00Z",
    createdAt: "2024-05-01T10:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z",
    createdBy: { id: "user-5", name: "Marketing Team" },
    questions: [
      { id: "q1", type: "RATING", label: "Overall event experience", required: true },
      { id: "q2", type: "RATING", label: "Content relevance", required: true },
      { id: "q3", type: "RATING", label: "Speaker quality", required: true },
      { id: "q4", type: "NPS", label: "Would you attend future events?", required: true },
      { id: "q5", type: "TEXT", label: "What topics would you like covered?", required: false },
    ],
  },
  {
    id: "tmpl-skills-assessment",
    name: "Skills Assessment Quiz",
    description: "Self-assessment quiz to evaluate team member skills and identify training needs.",
    kind: "QUIZ",
    category: "ASSESSMENT",
    isPublished: true,
    isDefault: false,
    version: 1,
    questionCount: 20,
    estimatedTime: 15,
    usageCount: 2,
    lastUsedAt: "2024-10-01T09:00:00Z",
    createdAt: "2024-08-01T11:00:00Z",
    updatedAt: "2024-09-15T14:00:00Z",
    createdBy: { id: "user-6", name: "Ted Pateros" },
    questions: [
      { id: "q1", type: "MULTIPLE_CHOICE", label: "Which tool do you use for project management?", required: true },
      { id: "q2", type: "RATING", label: "Rate your proficiency in video editing", required: true },
      { id: "q3", type: "RATING", label: "Rate your proficiency in graphic design", required: true },
      { id: "q4", type: "CHECKBOXES", label: "Select tools you are proficient in", required: true },
    ],
  },
];

export async function GET() {
  await new Promise((resolve) => setTimeout(resolve, 100));

  return NextResponse.json({
    data: MOCK_TEMPLATES,
    meta: {
      total: MOCK_TEMPLATES.length,
      published: MOCK_TEMPLATES.filter((t) => t.isPublished).length,
      byKind: {
        SURVEY: MOCK_TEMPLATES.filter((t) => t.kind === "SURVEY").length,
        POLL: MOCK_TEMPLATES.filter((t) => t.kind === "POLL").length,
        QUIZ: MOCK_TEMPLATES.filter((t) => t.kind === "QUIZ").length,
        FEEDBACK: MOCK_TEMPLATES.filter((t) => t.kind === "FEEDBACK").length,
      },
    },
    sandbox: true,
  });
}

export async function POST(request: Request) {
  const body = await request.json();

  const newTemplate = {
    id: `tmpl-${Date.now()}`,
    name: body.name || "New Template",
    description: body.description || "",
    kind: body.kind || "SURVEY",
    category: body.category || "CUSTOM",
    isPublished: false,
    isDefault: false,
    version: 1,
    questionCount: 0,
    estimatedTime: 0,
    usageCount: 0,
    lastUsedAt: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    createdBy: { id: "sandbox-user", name: "Sandbox User" },
    questions: [],
  };

  return NextResponse.json({
    data: newTemplate,
    sandbox: true,
    message: "Template created (sandbox mode - not persisted)",
  });
}
