import type { ResourceConfig } from "./types";

export const skillsResource: ResourceConfig = {
  name: "skills",
  label: "Skill",
  labelPlural: "Skills",
  model: "AgentSkill",
  module: "CONTENT_ENGINE",
  icon: "Brain",
  description: "AI agent skills for content generation and automation",

  fields: [
    {
      name: "id",
      label: "ID",
      type: "string",
      list: false,
      show: true,
      create: false,
      edit: false,
    },
    {
      name: "name",
      label: "Name",
      type: "string",
      list: true,
      filter: true,
      sortable: true,
      validation: { required: true, minLength: 2, maxLength: 100 },
    },
    {
      name: "slug",
      label: "Slug",
      type: "slug",
      list: true,
      description: "URL-friendly identifier (e.g., brief-creator)",
      validation: { required: true, maxLength: 50 },
    },
    {
      name: "description",
      label: "Description",
      type: "text",
      list: false,
      validation: { required: true },
    },
    {
      name: "category",
      label: "Category",
      type: "enum",
      enumName: "SkillCategory",
      list: true,
      filter: true,
      validation: { required: true },
      options: [
        { value: "CONTENT_CREATION", label: "Content Creation", color: "blue" },
        { value: "CONTENT_ANALYSIS", label: "Content Analysis", color: "green" },
        { value: "WORKFLOW", label: "Workflow", color: "purple" },
        { value: "DATA_PROCESSING", label: "Data Processing", color: "orange" },
        { value: "INTEGRATION", label: "Integration", color: "pink" },
      ],
    },
    {
      name: "isEnabled",
      label: "Enabled",
      type: "boolean",
      list: true,
      filter: true,
      defaultValue: true,
    },
    {
      name: "version",
      label: "Version",
      type: "string",
      list: true,
      defaultValue: "1.0.0",
    },

    // Configuration
    {
      name: "triggers",
      label: "Triggers",
      type: "json",
      list: false,
      description: "Events or conditions that invoke this skill",
      defaultValue: [],
    },
    {
      name: "inputs",
      label: "Inputs",
      type: "json",
      list: false,
      description: "Required input parameters",
      defaultValue: [],
    },
    {
      name: "outputs",
      label: "Outputs",
      type: "json",
      list: false,
      description: "Expected output format",
      defaultValue: [],
    },
    {
      name: "config",
      label: "Configuration",
      type: "json",
      list: false,
      description: "Runtime configuration options",
    },
    {
      name: "dependsOn",
      label: "Dependencies",
      type: "tags",
      list: false,
      description: "Other skill slugs this depends on",
    },
    {
      name: "requiredPermissions",
      label: "Required Permissions",
      type: "tags",
      list: false,
      description: "Permissions required to invoke this skill",
    },

    // Metrics
    {
      name: "invocationCount",
      label: "Invocations",
      type: "number",
      list: true,
      sortable: true,
      create: false,
      edit: false,
    },
    {
      name: "successRate",
      label: "Success Rate",
      type: "decimal",
      list: true,
      sortable: true,
      create: false,
      edit: false,
    },
    {
      name: "avgLatencyMs",
      label: "Avg Latency (ms)",
      type: "number",
      list: false,
      create: false,
      edit: false,
    },
    {
      name: "lastInvokedAt",
      label: "Last Invoked",
      type: "datetime",
      list: false,
      show: true,
      create: false,
      edit: false,
    },

    // Timestamps
    {
      name: "createdAt",
      label: "Created",
      type: "datetime",
      list: false,
      show: true,
      create: false,
      edit: false,
      sortable: true,
    },
    {
      name: "updatedAt",
      label: "Updated",
      type: "datetime",
      list: false,
      show: true,
      create: false,
      edit: false,
    },
  ],

  list: {
    columns: ["name", "slug", "category", "isEnabled", "version", "invocationCount", "successRate"],
    defaultSort: { field: "name", order: "asc" },
    pageSize: 20,
    searchable: true,
    searchFields: ["name", "slug", "description"],
    defaultFilters: ["category", "isEnabled"],
    rowActions: [
      {
        name: "edit",
        label: "Edit",
        icon: "Pencil",
        position: "row",
        type: "link",
        href: "/admin/skills/{{id}}/edit",
      },
      {
        name: "view",
        label: "View",
        icon: "Eye",
        position: "row",
        type: "link",
        href: "/admin/skills/{{id}}",
      },
      {
        name: "test",
        label: "Test",
        icon: "Play",
        position: "row",
        type: "link",
        href: "/content-engine/sandbox?skill={{slug}}",
      },
    ],
    headerActions: [
      {
        name: "create",
        label: "New Skill",
        icon: "Plus",
        position: "header",
        type: "link",
        href: "/admin/skills/create",
        color: "primary",
        permissions: ["ADMIN", "LEADERSHIP"],
      },
    ],
    emptyTitle: "No skills defined",
    emptyDescription: "Create your first AI skill to get started.",
  },

  create: {
    sections: [
      {
        id: "basic",
        title: "Basic Information",
        fields: ["name", "slug", "description", "category"],
      },
      {
        id: "status",
        title: "Status",
        fields: ["isEnabled", "version"],
      },
      {
        id: "definition",
        title: "Skill Definition",
        description: "Define how this skill works",
        fields: ["triggers", "inputs", "outputs"],
        collapsible: true,
        defaultOpen: true,
      },
      {
        id: "config",
        title: "Configuration",
        fields: ["config", "dependsOn", "requiredPermissions"],
        collapsible: true,
      },
    ],
    layout: "single",
    submitLabel: "Create Skill",
    redirectOnSuccess: "list",
  },

  edit: {
    sections: [
      {
        id: "basic",
        title: "Basic Information",
        fields: ["name", "slug", "description", "category"],
      },
      {
        id: "status",
        title: "Status",
        fields: ["isEnabled", "version"],
      },
      {
        id: "definition",
        title: "Skill Definition",
        fields: ["triggers", "inputs", "outputs"],
        collapsible: true,
      },
      {
        id: "config",
        title: "Configuration",
        fields: ["config", "dependsOn", "requiredPermissions"],
        collapsible: true,
      },
    ],
    layout: "single",
    submitLabel: "Save Changes",
    redirectOnSuccess: "show",
  },

  show: {
    sections: [
      {
        id: "overview",
        title: "Overview",
        fields: ["name", "slug", "category", "isEnabled", "version"],
        columns: 3,
      },
      {
        id: "description",
        title: "Description",
        fields: ["description"],
        columns: 1,
      },
      {
        id: "metrics",
        title: "Metrics",
        fields: ["invocationCount", "successRate", "avgLatencyMs", "lastInvokedAt"],
        columns: 4,
      },
      {
        id: "definition",
        title: "Skill Definition",
        fields: ["triggers", "inputs", "outputs"],
        columns: 1,
      },
      {
        id: "config",
        title: "Configuration",
        fields: ["config", "dependsOn", "requiredPermissions"],
        columns: 1,
      },
      {
        id: "meta",
        title: "Metadata",
        fields: ["id", "createdAt", "updatedAt"],
        columns: 3,
      },
    ],
    layout: "single",
    actions: [
      {
        name: "edit",
        label: "Edit Skill",
        icon: "Pencil",
        position: "toolbar",
        type: "link",
        href: "/admin/skills/{{id}}/edit",
        color: "primary",
      },
      {
        name: "test",
        label: "Test in Sandbox",
        icon: "Play",
        position: "toolbar",
        type: "link",
        href: "/content-engine/sandbox?skill={{slug}}",
      },
    ],
  },

  permissions: {
    list: ["ADMIN", "LEADERSHIP", "TEAM_LEAD"],
    show: ["ADMIN", "LEADERSHIP", "TEAM_LEAD"],
    create: ["ADMIN", "LEADERSHIP"],
    edit: ["ADMIN", "LEADERSHIP"],
    delete: ["ADMIN"],
  },

  audit: true,
  softDelete: false,
  tenantField: "organizationId",
};
